package it.polimi.ingsw.model.PlayerPackage;

public enum State {
    ENDMATCHSTATE,
    ERRORSTATE,
    HASSETADICESTATE,
    HASUSEDATOOLCARDACTIONSTATE,
    MATCHNOTSTARTEDYETSTATE,
    MUSTPASSTURNSTATE,
    MUSTSSETDILUENTEPERPASTASALDASTATE,
    MUSTSETPENNELLOPERPASTASALDASTATE,
    NOTYOURTURNSTATE,
    STARTTURNSTATE,
    MUSTSETSCHEMECARD,
    MATCHISSTARTEDSTATE;
}
