package it.polimi.ingsw.model;

import java.io.Serializable;

public enum State {
    // stati per il player
    ENDMATCHSTATE,
    ERRORSTATE,
    HASSETADICESTATE,
    HASUSEDATOOLCARDACTIONSTATE,
    MATCHNOTSTARTEDYETSTATE,
    MUSTPASSTURNSTATE,
    MUSTSSETDILUENTEPERPASTASALDASTATE,
    MUSTSETPENNELLOPERPASTASALDASTATE,
    NOTYOURTURNSTATE,
    STARTTURNSTATE,
    MUSTSETSCHEMECARD,
    FORCEENDMATCH,
    // stati per lo user
    ACTIVE,
    INACTIVE;
}
