package it.polimi.ingsw.model;


public enum TurnActions{
    SETDICE,
    GETMAPS,
    PASSTURN,
    LEAVEMATCHATTHEEND,
    USEALLTOOLCARD,
    SETTOOLCARDDICE,
    SETTOOLCARDDICEINTENSITY,
    SETSCHEMECARD,
    LEAVEMATCHBEFORESTARTING


}
